config/routes.rb
Rails.application.routes.draw do

  resources :orders

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "250x", :thumb => "75x75>", :show => "x350" }, :default_url => "default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  validates :name, :description,:category_id, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image

  belongs_to :user
  has_many :orders
  belongs_to :category
  has_many :reviews


  def average_rating
    if reviews.blank?
      0
    else
      reviews.average(:rating).round(2)
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  before_action :get_current_user_reviews


  # GET /listings
  # GET /listings.json
  def index
    if(params[:category].blank?)
      @listings = Listing.order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
    end
  end

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def search
    terms = params[:s].split(/ /)
    categories = []
    lists = []
    terms.each do |term|
      Category.where("name like '%#{term}%'").all.each do |cat|
        categories << cat.id
      end

      Listing.where("name like '%#{term}%' OR description like '%#{term}%'").all.each do |item|
        lists << item.id
      end
    end

    categories.uniq!
    lists.uniq!

    @listings = Listing.where("category_id in (#{categories.join(',')}) OR id in (#{lists.join(',')})").order("created_at DESC").paginate(:page => params[:page], :per_page => 9)

    render 'index'
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @reviews = Review.where(listing_id: @listing.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
    @review = Review.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category_id, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

  def get_current_user_reviews
    @user_reviews = []
    if user_signed_in?
      Review.where(user_id: current_user.id).all.each do |review|
        @user_reviews << review.listing_id
      end
    end
    @user_reviews
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="col-md-6">
<%= form_for @listing, :html => { :class => "form-horizontal listing", :multipart => true } do |f| %>

    <% if @listing.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h5 class="panel-title"><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h5>
      </div>
      <div class="panel-body">
        <ul>
        <% @listing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
      <%= f.text_field :name, :class => 'form-control' %>
    <%= error_span(@listing[:name]) %>
  </div>

    <div class="form-group">
      <%= f.label :category_id, :class => 'control-label' %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}, {class: 'form-control'} %>
      <%= error_span(@listing[:category_id]) %>
    </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label' %>
      <%= f.text_area :description, :class => 'form-control' %>
    <%= error_span(@listing[:description]) %>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'control-label' %>
      <%= f.text_field :price, :class => 'form-control' %>
    <%= error_span(@listing[:price]) %>
  </div>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label' %>
      <%= f.file_field :image, :class => 'form-control' %>
    <%= error_span(@listing[:image]) %>
  </div>

  <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                listings_path, :class => 'btn btn-default' %>
  </div>

<% end %>
</div>

app/views/listings/edit.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/listings/index.html.erb
<% if params[:category].blank? %>
    <div class="jumbotron">
      <h1>Handcrafted items from around the world.</h1>
      <h2>Discover one-of-a-kind items</h2>
    </div>

    <%= "<h1>Search Results</h1>".html_safe unless params[:s].blank? %>

<% else %>

    <div class="jumbotron category-header" style="background-image:url('<%= image_url @listings[0].category.image %>')">
      <h1>Handcrafted items from around the world.</h1>
      <h2>View all <%= @listings[0].category.name %> items</h2>
    </div>

    <h1><%= @listings.length %> <%= @listings[0].category.name %> items</h1>

<% end %>

<div class="center">
    <div class="row listing">
      <% @listings.each do |listing| %>
      <div class="col-sm-6 col-md-4 ">
        <div class="thumbnail">
          <div class="caption">
            <p><a href="<%= listings_path(category: listing.category.name) %>"><%= listing.category.name %></a></p>
          </div>
          <%= link_to image_tag(listing.image.url(:medium)), listing_path(listing) %>
          <div class="caption">
            <h3><%= link_to listing.name, listing_path(listing)  %></h3>
            <p><%= listing.description[0...80] %>...</p>
            <div class="center"><span class="star-rating" data-score="<%= listing.average_rating %>"></span> (<%= listing.reviews.length %> reviews)</div>
            <div class="pull-left"><p><%= number_to_currency(listing.price) %></p></div>
            <div class="pull-right"><%= link_to "Add to Cart", add_cart_path(listing),method: :post, class: "btn btn-primary", data: { no_turbolink: true } %></div>
            <div class="clearfix"></div>
            <p><%= "Sold by #{listing.user.name}" %></p>

          </div>
        </div>
      </div>
          <% end %>
    </div>
</div>

<br>

<%= will_paginate @listings, renderer: BootstrapPagination::Rails %>

app/views/listings/new.html.erb
<%- model_class = Listing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/listings/seller.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary pull-right" %>
<% end %>
<div style="clearfix"></div>
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Category</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
      <tr>
        <td><%= image_tag listing.image.url(:thumb) %></td>
        <td><%= listing.name %></td>
        <td><%= listing.category.name %></td>
        <td><%= listing.description %></td>
        <td><%= number_to_currency(listing.price) %></td>
        <td>

          <!-- Single button -->
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "View", listing, class: "btn btn-link" %></li>
              <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
              <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
            </ul>
          </div>


        </td>
      </tr>
  <% end %>
</table>

<br>

<%= will_paginate @listings, renderer: BootstrapPagination::Rails %>

<br>
<br>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image.url(:show) %>
    </div>
    <div class="reviews-summary">
      <span class="star-rating" data-score= <%= @avg_rating %> ></span> (<span><%= "#{@reviews.length} reviews" %></span>)
      <% if user_signed_in?  && @listing.user_id != current_user.id  && !@user_reviews.include?(@listing.id)%>
      | <%= link_to "Write Review", '#', class: "btn btn-link new-review-link" %>
      <% end %>

    </div>
  </div>
  <div class="col-md-6">
    <p><%= @listing.category.name %></p>
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= h(@listing.description ).gsub(/\n/, '<br/>').html_safe %></p>
    <div class="center">
      <%= link_to "Add to Cart", add_cart_path(@listing),method: :post, class: "btn btn-primary", data: { no_turbolink: true } %>

    </div>
    <!--<div class=""><p><%= @listing.user.name %></p></div>-->
  </div>
</div>

    <div class="reviews_container">
      <h2>Reviews</h2>
      <div id="review-form">
        <%= render partial: 'reviews/form'  %>
      </div>
      <% if @reviews.blank? %>
        <p>No reviews yet!</p>
      <% else %>
          <table class="table">
            <tbody>
          <% @reviews.each do |review| %>
                <tr>
                  <td>
                    <p><%= review.user.name %></p>
                    <p><%= review.created_at.strftime("%B %d, %Y") %></p>
                  </td>
                  <td>
                      <div class="star-rating" data-score= <%= review.rating %> ></div>
                      <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                  </td>
                </tr>
          <% end %>
            </tbody>
          </table>
      <% end %>
    </div>



<% if current_user && @listing.user_id == current_user.id %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %> |
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            listing_path,
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-link btn-danger' %>

<% end %>