config/routes.rb
Rails.application.routes.draw do

  resources :orders

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
    items = if hash["cart"] then
              hash["cart"]["items"].map do |item_data|
                CartItem.new item_data["product_id"], item_data["quantity"]
              end
            else
              []
            end

    new items
  end

  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find { |item| item.product_id == product_id }
    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def count
    @items.length
  end

  def serialize
    items = @items.map do |item|
      {
          "product_id" => item.product_id,
          "quantity" => item.quantity,
          "seller" => item.seller
      }
    end

    {
        "items" => items
    }
  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end

  def clear(seller)
    if seller
      @items = @items.map { |seller_item |
        seller_item if seller.to_s != seller_item.seller.to_s
      }
      @items.compact!
    else
      @items.clear
    end
  end


  def by_sellers
    sellers = {}
    @items.each do |item|
      tmp = @items.map { |seller_item |
          if item.seller == seller_item.seller
              seller_item
          end
      }
      tmp.compact!
      sellers[item.seller] = tmp
    end
    sellers
  end

  def seller_items (seller)
    tmp = @items.map { |seller_item |
      seller_item if seller.to_s == seller_item.seller.to_s
    }
    tmp.compact
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add
    @cart.add_item params[:id]
    session["cart"] = @cart.serialize
    product = Listing.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
  end

  def checkout
    @order_form = OrderForm.new user: User.new
    @client_token = Braintree::ClientToken.generate
  end

  def clear
    @cart.clear(params[:user_id])
    session["cart"] = @cart.serialize
    if session[:checking_out]
      session[:checking_out] = false
      redirect_to thankyou_path
    else
      redirect_to root_url, notice: "Cart Cleared"
    end

  end
end

app/views/carts/show.html.erb
<h1>Your cart</h1>

<% #@cart.clear
  unless @cart.empty?
    by_seller = @cart.by_sellers
    by_seller.each do |seller, items | %>

        <div class="panel panel-default">
          <div class="panel-heading"><h4>Order to <%= User.find(seller.to_i).name %></h4></div>
          <div class="panel-body">

            <table class="table table-hover">
              <thead>
              <tr>
                <th colspan="2">Product</th>
                <th class="text-right">Quantity</th>
                <th class="text-right">Unit Price</th>
                <th class="text-right">Total Price</th>
              </tr>
              </thead>
              <% total_price = 0 %>
              <% items.each do |item| %>
                  <tr>
                    <td><%= image_tag item.product.image.url(:thumb) %></td>
                    <td><%= link_to item.product.name, item.product %></td>
                    <td class="text-right"><%= item.quantity %></td>
                    <td class="text-right"><%= number_to_currency item.product.price %></td>
                    <td class="text-right"><%= number_to_currency item.total_price%></td>
                  </tr>
                  <% total_price = total_price + item.total_price %>
              <% end %>
              <tfoot>
              <tr>
                <td colspan="5" class="text-right"><b>Total: <%= number_to_currency total_price %></b></td>
              </tr>
              </tfoot>
            </table>
            <div class="text-right">
              <%= link_to "Proceed to Checkout", new_user_order_path(seller), class: "btn btn-primary", data: { no_turbolink: true } %>
            </div>
          </div>
        </div>
        <hr  />
    <% end %>



<% end %>