config/routes.rb
Rails.application.routes.draw do

  resources :orders

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/views/layouts/_cart.html.erb
<% if @cart %>
<p class="navbar-text navbar-right">
    <% if @cart.empty? %>
        Your cart is empty.
    <% else %>
        <%=link_to "You have #{pluralize @cart.count, "item"}.", cart_path %>
    <% end %>
</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">

  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_url %>">Etsy</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <form class="navbar-form  navbar-left" method="get" action="<%= search_path %>"><input class="form-control" type="text" name="s" placeholder="Search...." /></form>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse by Category <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
            <li><%= link_to category.name, listings_path(category: category.name) %></li>
            <% end %>
          </ul>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= render partial: 'layouts/cart' %>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Manage Listings", seller_path %></li>
                <li><%= link_to "Add new item", new_listing_path %></li>
                <li><%= link_to "Sales History", sales_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Purchase History", purchases_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>




      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Etsydemo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>

    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>

  </head>
  <body>

    <%= render "layouts/header" %>


    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  <%= render "layouts/footer" %>

<script>


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-19153316-3', 'auto');
  ga('send', 'pageview');

</script>

  </body>
</html>